# Use the official Elasticsearch image from Docker Hub
FROM docker.elastic.co/elasticsearch/elasticsearch:latest

# Add your custom configurations if needed
# COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Expose Elasticsearch ports
EXPOSE 9200 9300
